spring:
  profiles:
    active: local
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      auto-offset-reset: earliest
    properties:
      schema:
        registry:
          url: http://localhost:8001/api/schema-registry
server:
  port: 8089


customer:
  topic: customer-topic
  group:
    id: customer-group-id

